### ISSUE TITLE
Make Guzzle work with proxy variable if any set on system.

### ISSUE THREAD

**Issue by dvid** [continuousphp/sdk#1]
As guzzle doesn't read natively the proxy settings of the system, it throws an error while fopen(); when downloading a package. It should try to read the variable if any set, then continue on it's build task with the variable config passed.

**Comment by gboddin** [comment]
The issue's not with guzzle which handle HTTP proxies fine, but with continousphp sdk : 
https://github.com/continuousphp/sdk/blob/master/src/Client.php#L49

The stream context should respect the http(s)_proxy environment variables.

This issue is blocking as it dissallow any downloads of the cphp packages trough any proxied internet access.

**Comment by ppaulis** [comment]
@gboddin I will make sure that @fdewinne  gets the message. But if you already have the fix at hand, just can also drop me a PR :)

Thanks for reporting!

**Comment by gboddin** [comment]
Sadly I don't ;) (yet) 

Otherwise I would happily have done so, but we're busy implementing deployments in our internal environments ;)

**Comment by ppaulis** [comment]
@gboddin OK :) I'll make sure to discuss this with Frederic today and get back to you shortly.

Thanks!

**Comment by fdewinne** [comment]
@gboddin I'll check this (and fix it tomorrow) behind your proxy. What's strange is our SDK is completely based on guzzle http that should manage proxies. Maybe an issue in guzzle http stream...

**Comment by gboddin** [comment]
Hey, @fdewinne .

I did some research yesterday and I came to the following conclusions :

Using the (context) stream handler from guzzle would indeed make sure you use the same settings, BUT : 

When using fopen on an https url, you will fall back to the PHP's ssl context stream described here : 
http://php.net/manual/en/context.ssl.php

There's actually no option to set the proxy in this context, so I'm pretty sure Guzzle cannot cope with this.

One solution would be to clone the curl resources from guzzle (I have no clue how to do this) and apply the following method : 

``` php
$fp = fopen ('localfile.tmp', 'w'); //This is the file where we save the    information
curl_setopt($ch, CURLOPT_FILE, $fp); // write curl response to file
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_exec($ch); // get curl response
curl_close($ch);
fclose($fp);
```

**Comment by fdewinne** [comment]
Just switch to curl. It still work without proxy then I let you test on your side.

Thank you for your feedback

**Comment by fdewinne** [comment]
@dvid just told me it works fine. Then I close the issue.

Thank you for your help!

**Comment by gboddin** [comment]
Super thanks !
